city_dictionary = {
    "PAR": "Paris",
    "NYC": "New York City",
    "LON": "London",
    "TLV": "Tel Aviv",
    "BER": "Berlin",
    "ROM": "Rome",
    "SYD": "Sydney",
    "TOK": "Tokyo",
    "MAD": "Madrid",
    "AMS": "Amsterdam",
    "IST": "Istanbul",
    "BKK": "Bangkok",
    "DEL": "Delhi",
    "CAI": "Cairo",
    "MEX": "Mexico City",
    "BUE": "Buenos Aires",
    "RIO": "Rio de Janeiro",
    "PEK": "Beijing",
    "MOS": "Moscow",
    "NBO": "Nairobi",
    "TOR": "Toronto",
    "SFO": "San Francisco",
    "CHI": "Chicago",
    "HOU": "Houston",
    "SYD": "Sydney",
    "VAN": "Vancouver",
    "LIM": "Lima",
    "ATH": "Athens",
    "JNB": "Johannesburg",
    "CPT": "Cape Town",
    "DUB": "Dublin",
    "HKG": "Hong Kong",
    "SIN": "Singapore",
    "KUL": "Kuala Lumpur",
    "DXB": "Dubai",
    "AMS": "Amsterdam",
    "BRU": "Brussels",
    "ZRH": "Zurich",
    "VIE": "Vienna",
    "STO": "Stockholm",
    "OSL": "Oslo",
    "HEL": "Helsinki",
    "CPH": "Copenhagen",
    "WAW": "Warsaw",
    "PRG": "Prague",
    "BUD": "Budapest",
    "ATH": "Athens",
    "WAW": "Warsaw",
    "LIS": "Lisbon",
    "WAS": "Washington, D.C.",
    "BOS": "Boston",
    "ATL": "Atlanta",
    "MIA": "Miami",
    "LAS": "Las Vegas",
    "DEN": "Denver",
    "SEA": "Seattle",
    "PHX": "Phoenix",
    "MSP": "Minneapolis",
    "ORD": "Chicago O'Hare",
    "DTW": "Detroit",
    "DFW": "Dallas-Fort Worth",
    "IAH": "Houston",
    "LAX": "Los Angeles",
    "SFO": "San Francisco",
    "JFK": "John F. Kennedy",
    "LGA": "LaGuardia",
    "EWR": "Newark",
    "MCO": "Orlando",
    "TPA": "Tampa",
    "MIA": "Miami",
    "FLL": "Fort Lauderdale",
    "RSW": "Fort Myers",
    "TPA": "Tampa",
    "MCO": "Orlando",
    "SAN": "San Diego",
    "PHX": "Phoenix",
    "LAS": "Las Vegas",
    "DEN": "Denver",
    "DFW": "Dallas-Fort Worth",
    "IAH": "Houston",
    "ATL": "Atlanta",
    "BOS": "Boston",
    "MSP": "Minneapolis",
    "DTW": "Detroit",
    "ORD": "Chicago O'Hare",
    "LAX": "Los Angeles",
    "SEA": "Seattle",
    "SFO": "San Francisco",
    "JFK": "John F. Kennedy",
    "LGA": "LaGuardia",
    "EWR": "Newark",
    "PHL": "Philadelphia",
    "BWI": "Baltimore",
    "IAD": "Washington Dulles",
    "DCA": "Washington National",
    "YYZ": "Toronto Pearson",
    "YUL": "Montreal",
    "YVR": "Vancouver",
    "YYC": "Calgary",
    "YEG": "Edmonton",
    "YWG": "Winnipeg",
    "YQR": "Regina",
    "YXE": "Saskatoon",
    "YOW": "Ottawa",
    "YHZ": "Halifax",
}